[workspace]
members = ["aocutil", "day*"]
resolver = "2"

[workspace.dependencies]
aocutil = { path = "./aocutil" }
indoc = "2.0.5"
regex = "1.11.1"
itertools = "0.13.0"
pathfinding = "4.12.0"

[profile.release]
debug = true
